name: Run MLB Rosters Update

on:
  schedule:
    - cron: "0 14 * * *"   # 10 AM ET
    - cron: "0 15 * * *"   # 11 AM ET
    - cron: "0 16 * * *"   # 12 PM ET
    - cron: "0 17 * * *"   # 1 PM ET
    - cron: "0 18 * * *"   # 2 PM ET
    - cron: "0 19 * * *"   # 3 PM ET
    - cron: "0 20 * * *"   # 4 PM ET
    - cron: "0 21 * * *"   # 5 PM ET
    - cron: "0 22 * * *"   # 6 PM ET
    - cron: "0 23 * * *"   # 7 PM ET
    - cron: "0 00 * * *"   # 8 PM ET
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r backend/python_pipelines/python_requirements.txt

      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run MLB Rosters Update
        run: python backend/python_pipelines/data_scheduler/run_roster_update.py
